# AngeRouter v2.1 - HTTP daemon config
# DO NOT DISTRIBUTE

[auth]
admin_user=admin
admin_pass=AngeRouter2024!
secret_key=AngeVirus{firmware_creds_in_plaintext}

[network]
wan_ip=0.0.0.0
lan_ip=192.168.1.1
telnet_enable=1
telnet_port=23

[debug]
# backdoor activé en dev, à désactiver en prod
backdoor_port=31337
backdoor_pass=shadow_bytes_dev
